config/routes.rb
FirstApp::Application.routes.draw do
  get "sessions/new"

  get "pages/home"

  get "pages/contact"

  get "pages/about"

  get "pages/help"
  resources :microposts

 resources :users do
	member do
 	  get :following, :followers
	end
	collection do
	  get :tigers
	end

end

	resources :sessions, :only => [:new, :create, :destroy]
	resources :relationships, :only => [:create, :destroy]

	match '/signup',  :to => 'users#new'
	match '/signin', :to => 'sessions#new'
	match '/signout', :to => 'sessions#destroy'
   resources :microposts, :only => [:create, :destroy]

   root :to => "pages#home"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title %></title>
    <%= csrf_meta_tag %>
	<%= javascript_include_tag :defaults %>
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
    <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
    <%= stylesheet_link_tag 'custom', :media => 'screen' %>
  </head>
  <body>
    <div class="container">
      <header>
        <%= image_tag("logo.png", :alt => "Sample App", :class => "round") %>
        <nav class="round">
          <ul>
            <li><%= link_to "Home", '#' %></li>
	<% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
	    <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
	<% end %>

            <li><%= link_to "Help", '#' %></li>
            <% if signed_in? %>
		<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
	    <% else %>
		<li><%= link_to "Sign in", signin_path %></li>
	    <% end %>

          </ul>
        </nav>
      </header>
      <section class="round">
        <%= yield %>
      </section>

<footer>
  <nav class="round">
    <ul>
      <li><a href="/pages/about">About</a></li>
      <li><a href="/pages/contact">Contact</a></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
    </ul>
  </nav>
</footer>



    </div>
  </body>
</html>